name: CI

on:
  push:
    branches:
      - master
      - 'stage/**'
  pull_request:

jobs:
  build:
    name: ${{ matrix.name || 'Build' }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell || 'sh' }}
    strategy:
      matrix:
        include:
        - name: Ubuntu
          os: ubuntu-latest
        - name: MacOS
          os: macos-latest
        - name: Windows
          os: windows-latest
          shell: msys2 {0}
      # complete all jobs
      fail-fast: false
    steps:
    - name: Install MSYS2 (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        install: curl unzip
    - name: Install Elan
      shell: bash -euo pipefail {0}
      run: |
        curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y --default-toolchain none
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check Lean
      run: lean --version
    - name: Build
      run: lake build
    - name: Upload Build
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: build
    - name: Test
      run: ./test.sh
